slice_name: Beneficiary Gender
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 8__table
  viz_type: pie
  groupby:
  - gender
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: beneficiary_count
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 205
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(beneficiary_count)
    optionName: metric_03auirb1yil2_pgqkzdzgdad
  adhoc_filters: []
  row_limit: 100
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 5
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: e6756536-eb80-436d-a226-bf3790b81987
version: 1.0.0
dataset_uuid: cd687fe9-75dd-4fdc-8d0e-3d2292ef24a1
