slice_name: Registry Types
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 11__table
  viz_type: pie
  slice_id: 23
  groupby:
  - registrant_type
  metric: count
  adhoc_filters: []
  row_limit: 100
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: '10'
  show_legend: true
  legendType: plain
  legendOrientation: bottom
  label_type: key
  number_format: .3s
  date_format: smart_date
  show_labels: true
  labels_outside: true
  outerRadius: 77
  donut: true
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 17
query_context: '{"datasource":{"id":11,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["registrant_type"],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":100,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"11__table","viz_type":"pie","slice_id":23,"groupby":["registrant_type"],"metric":"count","adhoc_filters":[],"row_limit":100,"sort_by_metric":true,"color_scheme":"supersetColors","show_labels_threshold":"10","show_legend":true,"legendType":"plain","legendOrientation":"bottom","label_type":"key","number_format":".3s","date_format":"smart_date","show_labels":true,"labels_outside":true,"outerRadius":77,"donut":true,"innerRadius":30,"extra_form_data":{},"dashboards":[17],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 8682ab9a-5789-46eb-a26f-f2d2096194e8
version: 1.0.0
dataset_uuid: c7aba30c-aedb-43da-b474-5b3458afd812
