slice_name: Shipped to Bank
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 5__table
  viz_type: big_number_total
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: number_of_disbursements_shipped
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 65
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(number_of_disbursements_shipped)
    optionName: metric_f2aio4sterl_woehiixkzvn
  adhoc_filters:
  - clause: WHERE
    subject: funds_available_latest_timestamp
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 3
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"filters":[{"col":"funds_available_latest_timestamp","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"number_of_disbursements_shipped","description":null,"expression":null,"filterable":true,"groupby":true,"id":65,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(number_of_disbursements_shipped)","optionName":"metric_f2aio4sterl_woehiixkzvn"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"5__table","viz_type":"big_number_total","metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"number_of_disbursements_shipped","description":null,"expression":null,"filterable":true,"groupby":true,"id":65,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(number_of_disbursements_shipped)","optionName":"metric_f2aio4sterl_woehiixkzvn"},"adhoc_filters":[{"clause":"WHERE","subject":"funds_available_latest_timestamp","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","extra_form_data":{},"dashboards":[3],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: d23184c6-0ba4-4eb5-bfa2-062745789971
version: 1.0.0
dataset_uuid: 8f8d7e44-4f7e-40d1-a3eb-61a6eb20817d
