slice_name: Total Disbursement Amount
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 2__table
  viz_type: big_number_total
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_disbursement_amount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 16
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(total_disbursement_amount)
    optionName: metric_4amh660g2d_qe5hn14v3vs
  adhoc_filters:
  - clause: WHERE
    subject: disbursement_schedule_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 3
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"filters":[{"col":"disbursement_schedule_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_disbursement_amount","description":null,"expression":null,"filterable":true,"groupby":true,"id":16,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(total_disbursement_amount)","optionName":"metric_4amh660g2d_qe5hn14v3vs"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"2__table","viz_type":"big_number_total","metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_disbursement_amount","description":null,"expression":null,"filterable":true,"groupby":true,"id":16,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(total_disbursement_amount)","optionName":"metric_4amh660g2d_qe5hn14v3vs"},"adhoc_filters":[{"clause":"WHERE","subject":"disbursement_schedule_date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","extra_form_data":{},"dashboards":[3],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: d3210fd9-17db-4bee-b0eb-9ce09305947f
version: 1.0.0
dataset_uuid: 1db6e6bb-a67f-44e2-9614-70f3223921f6
